// /**
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/ce7aRUdvtLu
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Inter } from 'next/font/google'

// inter({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import { Button } from "@/components/ui/button"
// import Link from "next/link"
// import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
// import { Textarea } from "@/components/ui/textarea"
// import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"

// export function ChatlogComponent() {
//   return (
//     <div className="grid min-h-screen w-full grid-cols-[280px_1fr] overflow-hidden">
//       <div className="flex flex-col border-r bg-muted/40">
//         <div className="flex h-14 items-center justify-between border-b px-4">
//           <h2 className="text-lg font-semibold">Chat History</h2>
//           <Button variant="ghost" size="icon">
//             <SearchIcon className="h-5 w-5" />
//             <span className="sr-only">Search</span>
//           </Button>
//         </div>
//         <div className="flex-1 overflow-auto p-4">
//           <div className="grid gap-4">
//             <Link
//               href="#"
//               className="flex items-center gap-3 rounded-md bg-muted p-3 transition-colors hover:bg-muted/50"
//               prefetch={false}
//             >
//               <Avatar className="h-10 w-10 border">
//                 <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
//                 <AvatarFallback>AC</AvatarFallback>
//               </Avatar>
//               <div className="flex-1 truncate">
//                 <p className="font-medium">Acme Inc</p>
//                 <p className="text-sm text-muted-foreground">Hey, can you help me with...</p>
//               </div>
//               <span className="text-xs text-muted-foreground">2h</span>
//             </Link>
//             <Link
//               href="#"
//               className="flex items-center gap-3 rounded-md bg-muted p-3 transition-colors hover:bg-muted/50"
//               prefetch={false}
//             >
//               <Avatar className="h-10 w-10 border">
//                 <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
//                 <AvatarFallback>JD</AvatarFallback>
//               </Avatar>
//               <div className="flex-1 truncate">
//                 <p className="font-medium">John Doe</p>
//                 <p className="text-sm text-muted-foreground">I have a question about...</p>
//               </div>
//               <span className="text-xs text-muted-foreground">1d</span>
//             </Link>
//             <Link
//               href="#"
//               className="flex items-center gap-3 rounded-md bg-muted p-3 transition-colors hover:bg-muted/50"
//               prefetch={false}
//             >
//               <Avatar className="h-10 w-10 border">
//                 <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
//                 <AvatarFallback>JS</AvatarFallback>
//               </Avatar>
//               <div className="flex-1 truncate">
//                 <p className="font-medium">Jane Smith</p>
//                 <p className="text-sm text-muted-foreground">Did you see the new...</p>
//               </div>
//               <span className="text-xs text-muted-foreground">3d</span>
//             </Link>
//           </div>
//         </div>
//       </div>
//       <div className="flex flex-col">
//         <header className="flex h-14 items-center justify-between border-b bg-muted/40 px-4">
//           <h1 className="text-lg font-semibold">Chat</h1>
//           <Button variant="outline">Sign In</Button>
//         </header>
//         <div className="flex-1 overflow-auto p-4">
//           <div className="grid gap-4">
//             <div className="flex items-start gap-3">
//               <Avatar className="h-10 w-10 border">
//                 <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
//                 <AvatarFallback>AC</AvatarFallback>
//               </Avatar>
//               <div className="flex-1 rounded-md bg-muted p-3">
//                 <p>
//                   Hey, I was wondering if you could help me with something? I'm trying to set up a new project and I'm a
//                   bit stuck.
//                 </p>
//               </div>
//             </div>
//             <div className="flex items-start gap-3 justify-end">
//               <div className="flex-1 rounded-md bg-primary p-3 text-primary-foreground">
//                 <p>Sure, what's the issue?</p>
//               </div>
//               <Avatar className="h-10 w-10 border">
//                 <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
//                 <AvatarFallback>JD</AvatarFallback>
//               </Avatar>
//             </div>
//             <div className="flex items-start gap-3">
//               <Avatar className="h-10 w-10 border">
//                 <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
//                 <AvatarFallback>AC</AvatarFallback>
//               </Avatar>
//               <div className="flex-1 rounded-md bg-muted p-3">
//                 <p>
//                   Well, I'm trying to set up a new React project, but I'm not sure which libraries I should use. Do you
//                   have any recommendations?
//                 </p>
//               </div>
//             </div>
//           </div>
//         </div>
//         <div className="sticky bottom-0 flex w-full items-center gap-2 border-t bg-background p-4">
//           <Textarea
//             placeholder="Type your message..."
//             className="flex-1 resize-none rounded-md border border-input bg-background p-2 text-sm"
//           />
//           <Button variant="outline" className="shrink-0">
//             Send
//           </Button>
//           <DropdownMenu>
//             <DropdownMenuTrigger asChild>
//               <Button variant="outline" size="icon" className="shrink-0">
//                 <SaveIcon className="h-5 w-5" />
//                 <span className="sr-only">Save</span>
//               </Button>
//             </DropdownMenuTrigger>
//             <DropdownMenuContent align="end">
//               <DropdownMenuItem>
//                 <SaveIcon className="h-4 w-4 mr-2" />
//                 Save Message
//               </DropdownMenuItem>
//               <DropdownMenuItem>
//                 <TrashIcon className="h-4 w-4 mr-2" />
//                 Delete Message
//               </DropdownMenuItem>
//             </DropdownMenuContent>
//           </DropdownMenu>
//         </div>
//       </div>
//     </div>
//   )
// }

// function SaveIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z" />
//       <path d="M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7" />
//       <path d="M7 3v4a1 1 0 0 0 1 1h7" />
//     </svg>
//   )
// }


// function SearchIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <circle cx="11" cy="11" r="8" />
//       <path d="m21 21-4.3-4.3" />
//     </svg>
//   )
// }


// function TrashIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M3 6h18" />
//       <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
//       <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
//     </svg>
//   )
// }
